### ISSUE TITLE
Separate functionality in compute_bwd_err

### ISSUE THREAD

**Issue by jarlebring** [matrixfunctions/GraphMatFun.jl#54]
Currently, the function `compute_bwd_theta_exponential` does two things 1: computes the backward error function `bnd_rel_bwd_err`  2: Computes the intersection of `eps()/2` with `bnd_rel_bwd_err` using `fzero`.

I would prefer to have this in several functions:

* `compute_bnd_rel_bwd_err(:exp, graph, ; ... )`  
* `compute_bwd_err_theta(:exp,  ; bnd_rel_err=compute_bnd_rel_bwd_err(:exp, graph, ; ... ))`

The reason is that the fzero call often fails and in those situations one would be interested in the function. When `fzero` fails it throws an error so the information about the function is not available. 

Besides: The fzero often takes many iteartions. Instead of running fzero on `eps()/2=bnd_rel_bwd_err(x)`, we can run it on `log(eps()/2) = log(bnd_rel_bwd_err(x))`. It should be faster considering how the `bwd_err`- function behaves. This feature would be natural to incorporate in `compute_bwd_err_theta` eg as a kwarg.

**Comment by mfasi** [comment]
I've split `compute_bwd_theta_exponential` into ``compute_bnd_rel_bwd_err_exp(graph; ...)` and `compute_bwd_err_theta(;bnd_rel_err=compute_bnd_rel_bwd_err_exp(graph; ...))` in cc43276 and I've added the `use_log` kwarg to the latter in 8872636. The suffix `_exp` in the function names is due to the fact that I don't understand is the use of the symbol `:exp` in the argument list. I don't think it's meant to be use for dispatch, as it's a symbol and not a type.

**Comment by jarlebring** [comment]
Nice.

The reason I added `:exp` in the argument list and removed it from the function name was it seems cleaner wrt future functionality, and less hard-coded than in a function name. Since we only support `:exp` at the moment, the function would start with checking if `fun==:exp` and throw an error if this is not the case.  

It would have been nicer to handle this with dispatch (as you suggest) but I don't see how to do that without adding considerable amounts of code.

**Comment by jarlebring** [comment]
Ah... and the function `compute_bwd_theta_exp` is already independent of function whose backward error we analyze. So it can be renamed `compute_bwd_theta` without the use of `:exp`.   (Okay the default kwarg refers to the exponential but that can remain so even if we rename the function.)

**Comment by jarlebring** [comment]
Looks good to me!
