### ISSUE TITLE
References not appearing in documentation

### ISSUE THREAD

**Issue by jarlebring** [matrixfunctions/GraphMatFun.jl#55]
The docscring references do not appear in the docs page, eg https://matrixfunctions.github.io/GraphMatFun.jl/dev/generators/   `graph_ps` etc.

**Comment by mfasi** [comment]
> A problem with the footnotes is that they are repeated at the bottom of the generated page, so that there is no re-use.

Thanks for spotting this, it's quite unfortunate. The easiest thing to do would be to revert the format for the references, I think. If you have better solutions please let me know, otherwise I'll take up this one (I caused the issue in the first place, after all).

**Comment by jarlebring** [comment]
Yes. It seems the advanced way of doing references doesnt display very nicely. I agree to reverting.
