### ISSUE TITLE
Inaccuracy in exponential of matrix with high norm value 

### ISSUE THREAD

**Issue by YuvalBernard** [matrixfunctions/GraphMatFun.jl#71]
First of all, I have to say that this package is amazing!
However, I've encountered an example where the matrix exponential methods don't work correctly (except `graph_exp_native_jl`).
The matrix is 7x7:
`A = [
 -3512.0           8.4694e5     0.0      600.0             0.0           0.0    0.0
    -8.4694e5  -3512.0       6283.19       0.0           600.0           0.0    0.0
     0.0       -6283.19       -26.0        0.0             0.0         600.0   14.0
    12.0           0.0          0.0   -40600.0             3.58321e5     0.0    0.0
     0.0          12.0          0.0       -3.58321e5  -40600.0        6283.19   0.0
     0.0           0.0         12.0        0.0         -6283.19       -602.0    0.04
     0.0           0.0          0.0        0.0             0.0           0.0    0.0
]`
where `norm(A) = 1.3e6`.
Using the native Julia implementation:
`exp(A) = [
 3.7026e-11   -1.51691e-13  4.99098e-9   8.64083e-11  -9.72518e-12  4.99055e-9   0.0071976
 1.51691e-13  -6.21457e-16  2.04474e-11  3.54004e-13  -3.98428e-14  2.04456e-11  2.96129e-5
 4.99098e-9   -2.04474e-11  6.72767e-7   1.16475e-8   -1.31092e-9   6.72708e-7   0.970212
 1.72817e-12  -7.08007e-15  2.32951e-10  4.03306e-12  -4.53917e-13  2.32931e-10  0.000329305
 1.94504e-13  -7.96856e-16  2.62184e-11  4.53917e-13  -5.10879e-14  2.62161e-11  3.70713e-5
 9.98109e-11  -4.08912e-13  1.34542e-8   2.32931e-10  -2.62161e-11  1.3453e-8    0.0190193
 0.0           0.0          0.0          0.0           0.0          0.0          1.0
]`
Using https://github.com/matrixfunctions/GraphMatFunData/blob/main/data/generated/exp/exp_sid_m6.jl
`exp_sid_m6(A) = [
  2.97826e118   2.97286e117  -2.21034e116   6.38955e114  -3.60893e115  -6.09244e112  -3.34333e110
 -2.97286e117   2.97842e118   2.11449e115   3.60877e115   6.39016e114  -4.24532e113  -3.65511e111
 -2.21034e116  -2.11449e115   1.6404e114   -4.62994e112   2.67926e113   4.39009e110   2.36867e108
  1.27791e113  -7.21753e113  -9.25988e110  -9.03641e110  -2.06996e110   1.08165e109   8.86299e106
  7.21786e113   1.27803e113  -5.35851e111   2.06996e110  -9.03776e110  -1.93249e108  -1.49392e106
 -1.21849e111   8.49065e111   8.78019e108   1.08165e109   1.93249e108  -1.29889e107  -1.04235e105
  0.0           0.0           0.0           0.0           0.0           0.0           1.0
]`
which is obviously wrong...
Honestly I have no idea what caused this. I've also reproduced the error in MATLAB using the `expm` and https://github.com/matrixfunctions/GraphMatFunData/blob/main/data/generated/exp/exp_sid_m6.jl

**Comment by jarlebring** [comment]
This is not a bug, but rather a restriction in applicability (as explained in the manuscript https://arxiv.org/pdf/2107.12198.pdf). The function `exp_sid_m6` is only valid for matrices where all eigenvalues are smaller than 2.219 in modulus. You can see these values in this table 
![Screenshot_20230922_165014](https://github.com/matrixfunctions/GraphMatFun.jl/assets/11163595/fababfd2-db01-4156-b335-ce2c7f1c594c)

You can get around it by doing scaling-and-squaring. For your matrix it seems one needs 20 squarings. 

```
julia> p=20; norm(A/2^p)
1.241566521788209
```
and squaring phase
```
julia> B=exp_sid_m6(A/(2^p)); for j=1:p; B=B*B; end; E=B
7×7 Matrix{Float64}:
 3.70261e-11  -1.51691e-13  4.99098e-9   8.64084e-11  -9.72519e-12  4.99055e-9   0.00719761
 1.51691e-13  -6.21459e-16  2.04474e-11  3.54004e-13  -3.98428e-14  2.04456e-11  2.9613e-5
 4.99098e-9   -2.04474e-11  6.72766e-7   1.16475e-8   -1.31092e-9   6.72708e-7   0.970212
 1.72817e-12  -7.08008e-15  2.32951e-10  4.03306e-12  -4.53917e-13  2.32931e-10  0.000329305
 1.94504e-13  -7.96857e-16  2.62184e-11  4.53917e-13  -5.10879e-14  2.62161e-11  3.70713e-5
 9.9811e-11   -4.08913e-13  1.34542e-8   2.32931e-10  -2.62161e-11  1.3453e-8    0.0190193
 0.0           0.0          0.0          0.0           0.0          0.0          1.0
```
