### ISSUE TITLE
New minor version needed?

### ISSUE THREAD

**Issue by mfasi** [matrixfunctions/GraphMatFun.jl#72]
I fixed an incompatibility with Julia 1.9.2 and a few warnings. One of them is
```Julia
┌ GraphMatFun [456a00ab-810a-4bbb-9f06-6bc08c0a1e82]
│  WARNING: method definition for #compute_bwd_theta#67 at ~/.julia/packages/GraphMatFun/cqWZh/src/error_bounds.jl:205 declares type variable T but does not use it.
└  
```
which shows up when the package is pre-compiled (upon download from the Julia Registry). Should we advance to v1.0.1, so that the compilation warning disappears for new users?

**Comment by jarlebring** [comment]
Thanks. Sounds good!
