### ISSUE TITLE
New trivial `lincomb` nodes

### ISSUE THREAD

**Issue by mfasi** [matrixfunctions/GraphMatFun.jl#78]
One thing I noticed by looking at the generated C and Julia code is that we now have a number of new trivial `lincomb` nodes, such as
```
    X ← + α × A + 0 × B
```
which should really be
```
    X ← + α × A             (a)
```
or
```
X ← 1 × A
```
which is just a copy and should be removed. In fact, nodes of the form `(a)` could also be removed by pushing `α` to the corresponding coefficient(s) of subsequent `lincomb`s, although this seems a bit messier to do.

_Originally posted by @mfasi in https://github.com/matrixfunctions/GraphMatFun.jl/issues/77#issuecomment-1895619931_

**Comment by jarlebring** [comment]
This of optimization should not be done in the code generation in my opinion. A user can always run `compress_trivial!` before calling `gen_code` and those cases will be removed. It can be handled at graph-level. I think we get cleaner code-generation code if we see the code generator as being a bit stupid. Code generation philosophy: "Generate code for exactly this graph".  

`compress_trivial!` handles the first case (zero coeffs). Not sure about the second case (single coeff is one).

**Comment by mfasi** [comment]
I'll have a look and see if I can update `compress_trivial!` to handle the "copy" case.

I did remove terms with 0 coefficient in the C generator, but I can go roll back easily on that – I'd just need to remove

https://github.com/matrixfunctions/GraphMatFun.jl/blob/e4d6efd00cfb5b70b5748935deb4793166697f94/src/code_gen/gen_c_code.jl#L496-L498

**Comment by jarlebring** [comment]
I would be in favor of rolling that back. Maybe we first check that `compress_trivial!` actually does what I said. My memory is not perfect 🤯
