### ISSUE TITLE
`BigFloat` precision does not propagate through `eval_graph`

### ISSUE THREAD

**Issue by jarlebring** [matrixfunctions/GraphMatFun.jl#85]
The precision parameter of bigfloats seems to be lost in intermediate results in `eval_graph`:

```julia-repl
julia> myprec=100;
julia> Ab=BigFloat.(randn(2,3),precision=myprec);
julia> Bb=BigFloat.(randn(2,3),precision=myprec);
julia> cb=BigFloat.(randn(4),precision=myprec);
julia> (g,_)=graph_degopt(Degopt(Ab,Bb,cb));
julia> g.coeffs[:Ba3][1].prec   # This is okay
100
julia> p=eval_graph(g,BigFloat(0.2,precision=myprec));
julia> p.prec # This has become the default precision
256
```

**Comment by mfasi** [comment]
The problem is here

https://github.com/matrixfunctions/GraphMatFun.jl/blob/912beb5aa99888c60000a32cc4033e8a5b61694a/src/eval.jl#L91

`one(x)` seems to use the default `BigFloat` precision, not the precision of `x`.

```julia
julia> a = BigFloat(3, precision=100)
3.0
julia> a.prec
100
julia> one(a).prec
256
```

**Comment by jarlebring** [comment]
I have now found out that the kwarg precision in `BigFloat`  does not influence the precision for the opertaions with that object. It will always reduce to the global variable set by `setprecision`. This is by design of the `BigFloat`s: https://github.com/JuliaLang/julia/issues/56042#issuecomment-2400417139 

So our package actually does what is expected. Closing.

```julia
julia> myprec=100;
julia> setprecision(BigFloat,100)
100
julia> Ab=BigFloat.(randn(2,3));
julia> Bb=BigFloat.(randn(2,3));
julia> cb=BigFloat.(randn(4));
julia> (g,_)=graph_degopt(Degopt(Ab,Bb,cb));
julia> g.coeffs[:Ba3][1].prec   # This is okay
100
julia> p=eval_graph(g,BigFloat(0.2));
julia> p.prec # Now it works
100
```
